### ISSUE TITLE
"not a git repository" when running pre-commit hook on older git client

### ISSUE THREAD

**Issue by rogalski** [akaihola/darker#203] opened 2021-09-23 22:14 UTC
This bug is based on my experiments with `darker` on closed-source repo.
I am not at liberty to disclose any code. We'll have to work on recreating failure criteria on our own.

## Steps to reproduce:
1. Use darker as pre-commit hook with older Git (e.g. Git 2.7.x on Ubuntu 16.04 LTS)
2. Modify python file stored in subdirectory of repository, e.g. `/repository/subdir/file.py`
3. Run darker in pre-commit hook, e.g. using pre-commit.

## What happens:
1. Common root is resolved to `/repository/subdir`, not `/repository`
2. Unfortunately, older Git client runs hook with `GIT_DIR=.git` environment variable
3.  This environment variable disables traversal in search for actual `.git` directory
4. Git expects (due to cwd and env vars) that repo is in `/repository/subdirectory/.git`, not `/repository/.git`
5. Darker crashes with `not a repository` error.

## Possible fixes:
1. Leave as it is (treat old Git client as unsupported)
2. Drop `GIT_DIR` from our `git` subprocess invocations
3. Run traversal manually to always use repository top-level dir as `cwd`

**Comment by akaihola** [comment] 2021-09-24 06:51
Thanks @rogalski, that's very informative! This may be a duplicate of issue #112.

Could you try upgrading `darker` to `master` in your `.pre-commit.yaml`
```yaml
- repo: https://github.com/akaihola/darker
  rev: master
```
to see whether #185 fixed this (included in the soon-to-be-released [1.3.1 version](https://github.com/akaihola/darker/milestone/9?closed=1))?

**Comment by akaihola** [comment] 2021-10-05 15:03
Ping @rogalski, could you try if #203 is solved already in `master`?

**Comment by akaihola** [comment] 2021-10-31 19:28
I tried to reproduce the original `/repository/subdir/file.py` example in an Ubuntu 16.04 Docker image by installing Python 3.6 from the `deadsnakes` repository and then `pip install`ing `pre-commit`.

Unfortunately I couldn't get the `not a repository` error with any version of Darker.

I'm closing this issue – @rogalski please submit it again with step-by-step instructions for reproducing the problem if the latest Darker version still vails.

**Closed by akaihola** 2021-10-31 19:28 UTC
Labels: bug, question, maybe invalid?
